[package]
name = "echo-proto"
version = "0.1.0"
authors = ["Shawn Zhang <shawnzhang@lionfin.com.hk>"]

[dependencies]
bytes = "0.4"
futures = "0.1"
tokio-io = "0.1"
tokio-core = "0.1"
tokio-proto = "0.1"
tokio-service = "0.1"
